In [11]:
import pandas as pd

pd.set_option("display.max_rows", None)         # show all rows
pd.set_option("display.max_columns", None)      # show all columns
pd.set_option("display.width", None)            # auto-detect width (no wrapping cutoff)
pd.set_option("display.max_colwidth", None)     # don't truncate long strings
pd.set_option("display.expand_frame_repr", False)  # keep wide frames on one line in many consoles
pd.set_option("display.float_format", lambda x: f"{x:,.6f}")  # comma + 6 decimals

import warnings
warnings.filterwarnings("ignore")

In [12]:
df = pd.read_csv("../data/dc_parking_data.csv")

In [13]:
df.columns

Index(['OBJECTID', 'TICKET_NUMBER', 'ISSUE_DATE', 'ISSUE_TIME',
       'ISSUING_AGENCY_CODE', 'ISSUING_AGENCY_NAME', 'ISSUING_AGENCY_SHORT',
       'VIOLATION_CODE', 'VIOLATION_PROC_DESC', 'LOCATION', 'PLATE_STATE',
       'VEHICLE_TYPE', 'MULTI_OWNER_NUMBER', 'DISPOSITION_CODE',
       'DISPOSITION_TYPE', 'DISPOSITION_DESC', 'DISPOSITION_DATE',
       'FINE_AMOUNT', 'TOTAL_PAID', 'PENALTY_1', 'PENALTY_2', 'PENALTY_3',
       'PENALTY_4', 'PENALTY_5', 'XCOORD', 'YCOORD', 'LATITUDE', 'LONGITUDE',
       'MAR_ID', 'GIS_LAST_MOD_DTTM', 'ZCTA'],
      dtype='object')

In [14]:
df.head()

   OBJECTID  TICKET_NUMBER                 ISSUE_DATE  ISSUE_TIME  ISSUING_AGENCY_CODE                 ISSUING_AGENCY_NAME ISSUING_AGENCY_SHORT VIOLATION_CODE                               VIOLATION_PROC_DESC                 LOCATION PLATE_STATE  VEHICLE_TYPE  MULTI_OWNER_NUMBER  DISPOSITION_CODE DISPOSITION_TYPE    DISPOSITION_DESC        DISPOSITION_DATE  FINE_AMOUNT  TOTAL_PAID  PENALTY_1  PENALTY_2  PENALTY_3  PENALTY_4  PENALTY_5         XCOORD         YCOORD  LATITUDE  LONGITUDE         MAR_ID       GIS_LAST_MOD_DTTM          ZCTA
0  83861572      287252184  2025-01-01 05:00:00+00:00         314                    3  METROPOLITAN POLICE DPT-DISTRICT 3               MPD-3D           P001                   PARK ABREAST OF ANOTHER VEHICLE  SS 1400 BLK U STREET NW                       NaN            0.000000                 0            Other                 NaN                     NaN           50          50          0          0          0          0          0 397,117.190000 138,792.610000 38.917000 -77.033000 802,845.000000  2025/02/16 15:05:02+00 20,009.000000
1  83862192      294619021  2025-01-01 05:00:00+00:00        1350                   24     U.S. NATIONAL ZOOLOGICAL POLICE                  NZP           P007                                PARK IN A BUS ZONE  3131 CONNECTICUT AVE NW                       NaN            0.000000                 0            Other                 NaN                     NaN          100           0        100          0          0          0          0 395,188.030000 140,377.940000 38.931000 -77.055000 294,459.000000  2025/02/16 15:05:03+00 20,008.000000
2  83862193      294619032  2025-01-01 05:00:00+00:00        1351                   24     U.S. NATIONAL ZOOLOGICAL POLICE                  NZP           P007                                PARK IN A BUS ZONE  3131 CONNECTICUT AVE NW                       NaN            0.000000                 0            Other                 NaN                     NaN          100           0        100          0          0          0          0 395,188.030000 140,377.940000 38.931000 -77.055000 294,459.000000  2025/02/16 15:05:03+00 20,008.000000
3  83862195      294653833  2025-01-01 05:00:00+00:00        1620                    3  METROPOLITAN POLICE DPT-DISTRICT 3               MPD-3D           P003  RESIDENTIAL PERMIT PKING BEYOND LIMIT W/O PERMIT    REAR 1777 T STREET NW                       NaN            0.000000               134        Dismissed  DISM MAKE MISMATCH  2025/01/13 05:00:00+00           50           0          0          0          0          0          0 396,408.600000 138,659.310000 38.916000 -77.041000 241,478.000000  2025/02/16 15:05:03+00 20,009.000000
4  83862236      295109183  2025-01-01 05:00:00+00:00        2115                    1  METROPOLITAN POLICE DPT-DISTRICT 1               MPD-1D           P001                   PARK ABREAST OF ANOTHER VEHICLE     NS 700 BLK 7TH ST NE                       NaN            0.000000               106        Dismissed  DISM NOI SUBM LATE  2025/01/23 05:00:00+00           50           0          0          0          0          0          0 400,332.380000 136,856.050000 38.900000 -76.996000 800,861.000000  2025/02/16 15:05:03+00 20,002.000000

In [15]:
df.describe()

               OBJECTID        TICKET_NUMBER       ISSUE_TIME  ISSUING_AGENCY_CODE  VEHICLE_TYPE  MULTI_OWNER_NUMBER  DISPOSITION_CODE      FINE_AMOUNT       TOTAL_PAID        PENALTY_1        PENALTY_2        PENALTY_3        PENALTY_4        PENALTY_5           XCOORD           YCOORD         LATITUDE        LONGITUDE           MAR_ID           ZCTA
count  1,027,421.000000     1,027,421.000000 1,027,421.000000     1,027,421.000000      0.000000    1,027,378.000000  1,027,421.000000 1,027,421.000000 1,027,421.000000 1,027,421.000000 1,027,421.000000 1,027,421.000000 1,027,421.000000 1,027,421.000000 1,019,027.000000 1,019,027.000000 1,019,027.000000 1,019,027.000000 1,019,027.000000 985,930.000000
mean  84,474,814.953260 8,084,057,030.970328     1,251.739873            15.005957           NaN   42,550,817.014384          3.216047        59.707378        20.564124        15.133490         0.000000         0.000000         0.000005         0.000000   397,893.855759   137,599.438655        38.906261       -77.024314   787,475.885166  20,011.435283
std      347,626.753449   998,939,012.153774       528.519852             2.904774           NaN  196,202,304.864941         19.706751        48.025541        36.132188        37.170383         0.000000         0.000000         0.002206         0.000000     2,330.228920     2,304.369308         0.020754         0.026873   111,005.721096      11.298132
min   83,855,903.000000   260,541,223.000000         0.000000             0.000000           NaN            0.000000          0.000000         0.000000         0.000000         0.000000         0.000000         0.000000         0.000000         0.000000   390,147.800000   127,956.750000        38.819000       -77.114000   -38,388.000000  20,001.000000
25%   84,193,026.000000 8,276,250,754.000000       956.000000            15.000000           NaN            0.000000          0.000000        30.000000         0.000000         0.000000         0.000000         0.000000         0.000000         0.000000   396,410.040000   136,474.860000        38.896000       -77.041000   803,410.000000  20,003.000000
50%   84,471,142.000000 8,279,118,540.000000     1,228.000000            15.000000           NaN            0.000000          0.000000        50.000000         0.000000         0.000000         0.000000         0.000000         0.000000         0.000000   397,654.880000   137,372.730000        38.904000       -77.027000   807,447.000000  20,007.000000
75%   84,779,351.000000 8,282,627,076.000000     1,619.000000            15.000000           NaN            0.000000          0.000000       100.000000        30.000000         0.000000         0.000000         0.000000         0.000000         0.000000   399,140.710000   138,673.040000        38.916000       -77.010000   811,721.000000  20,018.000000
max   85,171,385.000000 9,110,549,700.000000     2,359.000000            80.000000           NaN  950,789,840.000000        201.000000     5,000.000000     1,000.000000     5,000.000000         0.000000         0.000000         1.000000         0.000000   407,817.910000   147,150.300000        38.992000       -76.910000   914,818.000000  20,037.000000

In [16]:
df.isna().sum()

OBJECTID                      0
TICKET_NUMBER                 0
ISSUE_DATE                    0
ISSUE_TIME                    0
ISSUING_AGENCY_CODE           0
ISSUING_AGENCY_NAME           0
ISSUING_AGENCY_SHORT          0
VIOLATION_CODE                0
VIOLATION_PROC_DESC         154
LOCATION                      0
PLATE_STATE                   0
VEHICLE_TYPE            1027421
MULTI_OWNER_NUMBER           43
DISPOSITION_CODE              0
DISPOSITION_TYPE              0
DISPOSITION_DESC         994376
DISPOSITION_DATE         994109
FINE_AMOUNT                   0
TOTAL_PAID                    0
PENALTY_1                     0
PENALTY_2                     0
PENALTY_3                     0
PENALTY_4                     0
PENALTY_5                     0
XCOORD                     8394
YCOORD                     8394
LATITUDE                   8394
LONGITUDE                  8394
MAR_ID                     8394
GIS_LAST_MOD_DTTM             0
ZCTA                      41491
dtype: int64

## EDA Plan

### GroupBys
- Month
- Quarter
- Day of Week
- Time of Day bands
- Issuing Agency

### Location
- Build a graph of lat/long w/ frequencies?
- Map w/ Zip codes